# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('budget', models.IntegerField()),
                ('max_trades', models.IntegerField()),
                ('leagues', models.ManyToManyField(through='fantalega.LeaguesTeams', to='fantalega.League')),
            ],
        ),
        migrations.AddField(
            model_name='leaguesteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.Team'),
        ),
    ]
