# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantalega.Team'),
        ),
    ]
