# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0004_auto_20160926_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.Team')),
            ],
        ),
    ]
