# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0005_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='fantalega.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fantalega.Team')),
                ('visit_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_team', to='fantalega.Team')),
            ],
        ),
    ]
