# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0006_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fantalega.League'),
        ),
    ]
