# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0008_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('day', models.IntegerField()),
                ('pts', models.FloatField(null=True)),
                ('won', models.IntegerField(null=True)),
                ('matched', models.IntegerField(null=True)),
                ('lost', models.IntegerField(null=True)),
                ('goals_made', models.IntegerField(null=True)),
                ('goals_conceded', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineupsPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.Lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantalega.Player')),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='players',
            field=models.ManyToManyField(related_name='player_lineups', through='fantalega.LineupsPlayers', to='fantalega.Player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lineups', to='fantalega.Team'),
        ),
    ]
