# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0014_auto_20161019_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='league',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_lineups', to='fantalega.League'),
        ),
    ]
