# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0016_auto_20161019_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='fantalega.League'),
            preserve_default=False,
        ),
    ]
