# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0018_player_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
