# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0024_player_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.CharField(default=False, max_length=9),
        ),
    ]
