# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0026_auto_20161020_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
