# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fantalega.validators
from fantalega.models import Season

season = Season.objects.all()[0]

class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0030_auto_20161025_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, validators=[fantalega.validators.validate_season_name])),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='league',
        ),
        migrations.AddField(
            model_name='match',
            name='dead_line',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='season',
            field=models.ForeignKey(default=season, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='fantalega.Season'),
            preserve_default=False,
        ),
    ]
