# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantalega', '0032_auto_20161028_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='dead_line',
            field=models.DateTimeField(null=True),
        ),
    ]
